export enum Permissions {
    CanEditAdmin = 'canEditAdmin',
    CanSeeFinancials = 'canSeeFinancials',
    CanEditSpray = 'canEditSpray',
    CanSeeOMS = 'isOMSUser',
    CanSeeHarvest = 'canSeeHarvest',
    CanSeePayroll = 'canSeePayroll',
    CanSeeTimesheets = 'canSeeTimesheets',
    CanSeeMaps = 'canSeeMaps',
    CanSeeInsights = 'canSeeInsights',
    CanSeeScout = 'canSeeScout',
    CanSeeAdminPayroll = 'canSeeAdminPayroll',
    CanEditOMSAdmin = 'canEditOMSAdmin',
    CanEditOrchardV2 = 'canEditOrchardV2',
    CanSeeSpectre = 'canSeeSpectre',
}
