export const GO_BACK = 'GO_BACK';
export const INIT_INVENTORY_COLUMNS = 'INIT_INVENTORY_COLUMNS';
export const INIT_INVENTORY_DATA = 'INIT_INVENTORY_DATA';

export const INIT_INVENTORY_OPERATORS_DATA = 'INIT_INVENTORY_OPERATORS_DATA';
export const INIT_INVENTORY_STORAGE_DATA = 'INIT_INVENTORY_STORAGE_DATA';

// Create new inventory page
export const SELECT_DATE = 'SELECT_DATE';
export const UPDATE_ORDER_ID = 'UPDATE_ORDER_ID';
export const FETCH_CHEMICAL_TYPES = 'FETCH_CHEMICAL_TYPES';
export const FETCH_OPERATORS_LIST = 'FETCH_OPERATORS_LIST';
export const UPDATE_RECEIVED_BY = 'UPDATE_RECEIVED_BY';
export const FETCH_SUPPLIER_LIST = 'FETCH_SUPPLIER_LIST';
export const SELECT_SUPPLIER = 'SELECT_SUPPLIER';
export const ADD_CHEM_ROW = 'ADD_CHEM_ROW';
export const DELETE_CHEM_ROW = 'DELETE_CHEM_ROW';
export const ADD_SUB_ROW = 'ADD_SUB_ROW';
export const DELETE_SUB_ROW = 'DELETE_SUB_ROW';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SELECT_CHEM_TYPE = 'SELECT_CHEM_TYPE';
export const SELECT_CHEM_NAME = 'SELECT_CHEM_NAME';
export const SET_PRICE = 'SET_PRICE';
export const SET_QUANTITY = 'SET_QUANTITY';
export const FETCH_LOCATION_LIST = 'FETCH_LOCATION_LIST';
export const SET_LOCATION = 'SET_LOCATION';
export const POST_INVENTORY_HISTORY = 'POST_INVENTORY_HISTORY';
export const CLEAR_NEW_INVENTORY = 'CLEAR_NEW_INVENTORY';
