export enum QueryKey {
    GetExportCountries = 'getExportCountries',
    GetVarietyDefault = 'getVarietyDefaultData',
    GetStaff = 'getStaff',
    GetVarityQCDefaults = 'getVarityQCDefaults',
    GetVarityPicks = 'getVarityPicks',
    GetVarityQualities = 'getVarityQualities',
    GetVarieties = 'getVarieties',
    GetStaffDetail = 'getStaffDetail',
    GetMetaData = 'getMetaData',
    GetMetaDataSectors = 'getMetaDataSectors',
    GetMetaDataLots = 'getMetaDataLots',
    GetMetaDataOrchardSites = 'getMetaDataOrchardSites',
    GetMetaDataBlocks = 'getMetaDataBlocks',
    GetMetaDataSubBlocks = 'getMetaDataSubBlocks',
    GetMetaDataRows = 'getMetaDataRows',
    GetMetaDataJobs = 'getMetaDataJobs',
    GetMetaDataLeaveTypes = 'getMetaDataLeaveTypes',
    GetNewAdminRateTreatementContractor = 'getNewAdminRateTreatementContractor',
    GetUnits = 'getUnits',
    GetLockedPayRuns = 'getLockedPayRuns',
}
